/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "on-surface-variant": "#434655",
        "primary": "#004ac6",
        "error-container": "#ffdad6",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#d2bbff",
        "surface": "#faf8ff",
        "inverse-primary": "#b4c5ff",
        "on-primary-container": "#eeefff",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3039",
        "secondary": "#006a61",
        "surface-tint": "#0053db",
        "on-primary-fixed": "#00174b",
        "background": "#faf8ff",
        "on-tertiary-fixed-variant": "#5a00c6",
        "outline-variant": "#c3c6d7",
        "error": "#ba1a1a",
        "surface-container": "#ededf9",
        "outline": "#737686",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-high": "#e7e7f3",
        "on-tertiary-container": "#f7edff",
        "tertiary-fixed": "#eaddff",
        "on-surface": "#191b23",
        "on-primary-fixed-variant": "#003ea8",
        "surface-bright": "#faf8ff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-dim": "#d9d9e5",
        "on-secondary-fixed": "#00201d",
        "on-error-container": "#93000a",
        "primary-container": "#2563eb",
        "secondary-fixed": "#89f5e7",
        "surface-variant": "#e1e2ed",
        "on-secondary-fixed-variant": "#005049",
        "surface-container-highest": "#e1e2ed",
        "on-secondary-container": "#006f66",
        "on-tertiary-fixed": "#25005a",
        "tertiary": "#6a1edb",
        "secondary-container": "#86f2e4",
        "inverse-on-surface": "#f0f0fb",
        "tertiary-container": "#8343f4",
        "secondary-fixed-dim": "#6bd8cb",
        "on-background": "#191b23"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "32px",
        "margin-desktop": "40px",
        "xs": "4px",
        "3xl": "64px",
        "gutter": "24px",
        "2xl": "48px",
        "md": "16px",
        "base": "4px",
        "margin-mobile": "16px",
        "sm": "8px",
        "lg": "24px"
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
